### ISSUE TITLE
Only one captcha is permitted per parent container. 

### ISSUE THREAD

**Issue by TelegramUsername** [hCaptcha/react-hcaptcha#129]
When I try to add hCaptcha to my form it shows `Only one captcha is permitted per parent container.`
Code:
```javascript
                <HCaptcha
                  sitekey=process.env.NEXT_PUBLIC_SITE_KEY
                  theme="dark"
                  size="normal"
                  ref={hcaptcha}
                  onVerify={(token) => {
                    setInfo({ ...info, hcaptcha_token: token });
                  }}
                />
```

Full Error:
```
next-dev.js?3515:25 Only one captcha is permitted per parent container. 
    at HCaptcha (webpack-internal:///./node_modules/@hcaptcha/react-hcaptcha/dist/index.js:62:37)
    at div
    at div
    at form
    at div
    at section
    at Contact (webpack-internal:///./pages/contact.jsx:123:75)
    at section
    at MyApp (webpack-internal:///./pages/_app.jsx:48:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20638)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23179)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:825:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:949:27)
```

**Comment by TelegramUsername** [comment]
> When I try to add hCaptcha to my form it shows `Only one captcha is permitted per parent container.` Code:
> 
> ```js
>                 <HCaptcha
>                   sitekey=process.env.NEXT_PUBLIC_SITE_KEY
>                   theme="dark"
>                   size="normal"
>                   ref={hcaptcha}
>                   onVerify={(token) => {
>                     setInfo({ ...info, hcaptcha_token: token });
>                   }}
>                 />
> ```

I am sure I have loaded hCaptcha Single Time

**Comment by TelegramUsername** [comment]
Caused by React 18 Strict Mode (An Issue is alredy present #128 )
