### ISSUE TITLE
TSC error TS2515

### ISSUE THREAD

**Issue by agat** [hCaptcha/react-hcaptcha#90]
I have this error after TS checking:

```
$ tsc --noemit
node_modules/@hcaptcha/react-hcaptcha/types/index.d.ts:30:15 - error TS2515: Non-abstract class 'HCaptcha' does not implement inherited abstract member 'render' from class 'Component<HCaptchaProps, HCaptchaState>'.
```

**Comment by chenzuo** [comment]
[16:27:15] Error: TypeScript error: C:/Users/Jed/Documents/code/x/web/gulp-html-adaptive-cards/node_modules/adaptivecards-fabric/lib/components/inputs/InputChoiceSetFabric.d.ts(4,22): Error TS2515: Non-abstract class 'InputChoiceSetFabric' does not implement inherited abstract member 'isSet' from class 'ReactInputElement'.
    at formatError (C:\Users\Jed\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\format-error.js:21:10)
    at Gulp.<anonymous> (C:\Users\Jed\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^4.0.0\log\events.js:33:15)
    at Gulp.emit (node:events:538:35)
    at Gulp.emit (node:domain:475:12)
    at Object.error (C:\Users\Jed\Documents\code\x\web\gulp-html-adaptive-cards\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (C:\Users\Jed\Documents\code\x\web\gulp-html-adaptive-cards\node_modules\now-and-later\lib\mapSeries.js:47:14)
    at f (C:\Users\Jed\Documents\code\x\web\gulp-html-adaptive-cards\node_modules\once\once.js:25:25)
    at f (C:\Users\Jed\Documents\code\x\web\gulp-html-adaptive-cards\node_modules\once\once.js:25:25)
    at tryCatch (C:\Users\Jed\Documents\code\x\web\gulp-html-adaptive-cards\node_modules\async-done\index.js:24:15)
    at done (C:\Users\Jed\Documents\code\x\web\gulp-html-adaptive-cards\node_modules\async-done\index.js:40:12)
[16:27:15] 'default' errored after 3.27 s
PS C:\Users\Jed\Documents\code\x\web\gulp-ht

**Comment by brdlyptrs** [comment]
Hi @agat can you check if this is still an issues with latest version?
